### ISSUE TITLE
App crash when we startPreview()

### ISSUE THREAD

**Issue by AmirthavalliSivaSankar** [GovindaPaliwal/AwesomeCodeScanner#3]
java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:519)
        at android.hardware.Camera.open(Camera.java:365)
        at com.gpfreetech.awesomescanner.ui.GpCodeScanner$InitializationThread.initialize(GpCodeScanner.java:822)
        at com.gpfreetech.awesomescanner.ui.GpCodeScanner$InitializationThread.run(GpCodeScanner.java:799)

**Comment by injamam4z** [comment]
I'm having the same issue on android 8.1

**Comment by NirjaSMT** [comment]
ya i also facing same
